os:
 - linux
before_script:
 - sudo apt-get update
 - sudo apt-get install qemu
 - sudo apt-get install binutils
 - sudo apt-get install build-essential
 - sudo apt-get install binutils-dev
 - sudo apt-get install libboost-all-dev
 - cd decaf

script: 
 - ./configure --disable-vmi --disable-tcg-taint > log1.txt
 - make
 - make distclean
 - reset

 - ./configure --disable-vmi --enable-tcg-taint > log2.txt
 - make
 - make distclean
 - reset

 - ./configure --enable-vmi --disable-tcg-taint > log3.txt
 - make
 - make distclean
 - reset

 - ./configure --enable-vmi --enable-tcg-taint > log4.txt
 - make
 - make distclean
 - reset

 - ./configure --enable-vmi --enable-tcg-taint --enable-tcg-ir-log > log4.txt
 - make
 - make distclean
language: c

